// <auto-generated />
using System;
using Chittak.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chittak.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chittak.Domain.Entities.AuthSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_auth_device");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Chittak.Domain.Entities.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .HasColumnType("text")
                        .HasColumnName("push_token");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("integer")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_devices_user");

                    b.HasIndex("UserId", "RegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_user_id_registration_id");

                    b.ToTable("devices", null, t =>
                        {
                            t.HasCheckConstraint("ck_devices_platform", "platform IN ('android', 'ios', 'linux', 'windows', 'macos')");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.DeviceIdentityKeyEntity", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("identity_key");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_identity_keys");

                    b.ToTable("device_identity_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_device_identity_keys_length", "octet_length(identity_key) = 64");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.MessageQueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("Envelope")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("envelope");

                    b.Property<short>("EnvelopeType")
                        .HasColumnType("smallint")
                        .HasColumnName("envelope_type");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("RecipientDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_device_id");

                    b.Property<Guid?>("SenderDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_device_id");

                    b.HasKey("Id")
                        .HasName("pk_message_queue");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_queue_expiry");

                    b.HasIndex("RecipientDeviceId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_message_queue_recipient_device_id_client_message_id");

                    b.HasIndex("RecipientDeviceId", "Id")
                        .HasDatabaseName("idx_queue_recipient");

                    b.ToTable("message_queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_message_queue_envelope_type", "envelope_type IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.OneTimePrekeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.HasKey("Id")
                        .HasName("pk_one_time_prekeys");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_otk_device");

                    b.HasIndex("DeviceId", "KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_one_time_prekeys_device_id_key_id");

                    b.ToTable("one_time_prekeys", null, t =>
                        {
                            t.HasCheckConstraint("ck_one_time_prekeys_public_key_length", "octet_length(public_key) = 32");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.PhoneVerificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_phone_verifications");

                    b.HasIndex("Phone", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_phone_verif");

                    b.ToTable("phone_verifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_phone_verifications_attempts", "attempts <= 5");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.SignedPrekeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("signature");

                    b.HasKey("Id")
                        .HasName("pk_signed_prekeys");

                    b.HasIndex("DeviceId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_signed_prekeys_device");

                    b.HasIndex("DeviceId", "KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_signed_prekeys_device_id_key_id");

                    b.ToTable("signed_prekeys", null, t =>
                        {
                            t.HasCheckConstraint("ck_signed_prekeys_public_key_length", "octet_length(public_key) = 32");

                            t.HasCheckConstraint("ck_signed_prekeys_signature_length", "octet_length(signature) = 64");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Discoverable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("discoverable");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone");

                    b.HasIndex("PhoneHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_hash");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_phone_e164", "phone ~ '^\\+[1-9][0-9]{6,14}$'");
                        });
                });

            modelBuilder.Entity("Chittak.Domain.Entities.AuthSessionEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.DeviceEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.UserEntity", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.DeviceIdentityKeyEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.DeviceEntity", "Device")
                        .WithOne()
                        .HasForeignKey("Chittak.Domain.Entities.DeviceIdentityKeyEntity", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_identity_keys_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.MessageQueueEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.DeviceEntity", "RecipientDevice")
                        .WithMany()
                        .HasForeignKey("RecipientDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_queue_devices_recipient_device_id");

                    b.Navigation("RecipientDevice");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.OneTimePrekeyEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_prekeys_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.SignedPrekeyEntity", b =>
                {
                    b.HasOne("Chittak.Domain.Entities.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signed_prekeys_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Chittak.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
