global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Configuration;
global using Testcontainers.PostgreSql;
global using System.Net;
global using System.Net.Http.Json;
global using Application.Common.Extensions;
global using Application.Features.Todo.Views;
global using AwesomeAssertions;
